---
- hosts: all
  vars_files:
    - vars/defaults.yml

  roles:
    - { role: users, sudo: true, user: vagrant }
    #- { role: ruby-deps, sudo: true }
    #- { role: postgresql, sudo: true }
    #- { role: rbenv }
    #- { role: ruby }

    # coming soon:
    #- bikeways
