---
- hosts: all
  vars_files:
    - vars/defaults.yml

  roles:
    - { role: deploy-user, sudo: true, user: vagrant }
    - { role: linux-prereqs, sudo: true }
    - { role: postgresql, sudo: true }
    - { role: nginx, sudo: true }
    #- { role: rbenv }
    #- { role: ruby }

    # coming soon:
    #- bikeways
