- name: Remove /opt/vagrant_ruby
  file: name=/opt/vagrant_ruby state=absent

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade existing linux packages
  apt: upgrade=dist update_cache=true
  async: 300
  poll: 15

- name: Install ruby/postgres dependencies
  action: apt pkg={{item}} state=installed update_cache=true
  async: 300
  poll: 15
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - gawk
    - git-core
    - git
    - libxml2-dev
    - libffi-dev
    - libyaml-dev
    - libssl-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libtool
    - libyaml-dev
    - nfs-common # make virtualbox faster
    - pkg-config
    - sqlite3
    - vim
    - zlib1g-dev
    - htop
    - iftop
    - python-pycurl # for postgresql playbook, uses apt_pkg