- hosts: webservers
  user: vagrant
  sudo: True
  vars_files:
    - vars.yml

  tasks:
    # see https://groups.google.com/forum/#!topic/ansible-project/ooAm8g3EEsU
      - name: Install python-pycurl
        apt: pkg=python-pycurl state=latest

      - name: Add PostgreSQL repo key
        apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

      - name: Add PostgreSQL repo
        apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

      - name: Install PostgreSQL
        apt: pkg=postgresql-9.3 state=latest update_cache=true

      - name: Copy valid pg_hba.conf
        template: src=templates/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf

      #- name: Copy valid postgresql.conf
      #  template: src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf

      - name: Restart PostgreSQL
        command: service postgresql restart