- name: set_global_ruby_version
  shell: cd; bash -lc "rbenv global {{ ruby_version }}"

# BUG: This will always mark as changed. Need to make a check/register.

- name: install_bundler
  shell: cd; bash -lc "gem install bundle bundler"
