- name: create deploy user
  user: name=deploy comment="deploy user" generate_ssh_key=yes state=present password={{password}} shell=/bin/bash

- name: authorize my SSH key to access all users
  authorized_key: user={{ item }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - vagrant
    - deploy

- name: copy ssh_config so that github doesn't do host verification
  action: copy src=ssh_config dest=~{{deploy}}/.ssh/config owner={{deploy}} group={{deploy}}

- name: add deploy as NOPASSWD to sudoers
  lineinfile: "dest=/etc/sudoers state=present line='{{deploy}} ALL=(ALL:ALL) NOPASSWD:ALL'"

- name: create www-data group
  group: name=www-data state=present

- name: create apps directory owned by deploy:www-data with setgid bit
  # note: 2755 => 2=setgid, 7=owner rwx, 5=group rx, 5=other rx
  file: name=~{{deploy}}/apps state=directory owner={{deploy}} group=www-data mode=2755
